config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats do
    resources :rentals, only: [:create, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :rentals
  has_one_attached :photo
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :flat
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :flats
  has_many :rentals
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(params_validation)
    @flat.user = current_user
    if @flat.save!
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def edit
    @flat = Flat.find(params[:id])
    authorize @flat
  end

  def update
    @flat = Flat.find(params[:id])
    authorize @flat
    @flat.update(params_validation)
    redirect_to flat_path(@flat)
  end

  private

  def params_validation
    params.require(:flat).permit(:rooms, :name, :adress, :price, :user_id, :created_at, :updated_at, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController

  def show
    # raise
    @rental = Rental.find(params[:id])
    authorize @rental
  end

  def create
    @rental = Rental.new(rental_params)
    @flat = flat.find(params[:flat_id])
    @rental.flat = @flat
    @rental.user = current_user
    @rental.save
    authorize @rental
    redirect_to dashboard_booking_path(@rental)
  end

 private

  def rental_params
    params.require(:rental).permit(:start_time, :end_time, :flat_id, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flats/index.html.erb
      <div class="container">
        <div class="div">
          <% @flats.each do |flat| %>
          <div class="col-3 mb-3 px-3 w-100">
            <%= link_to flat_path(flat) do %>
            <div class="div d-flex">
            <% if flat.photo.attached? %>
              <%= cl_image_tag flat.photo.key, height: 300, class: "img-card-top" %>
            <% else%>
              <%= "METTRE UNE IMAGE" %>
            <% end%>
              <ul class="list-group list-group-flush">
                <li class="list-group-item" style="center" id="pokename"> <%= flat.name %></li>
                <li class="list-group-item"> <strong>Adress:</strong> <%= flat.adress %> </li>
                <li class="list-group-item"> Price: <%= flat.price %> </li>
                <li class="list-group-item"> Rooms: <%= flat.rooms %></li>
              </ul>
            <% end %>
            </div>
          <% end %>
          </div>
      </div>
      </div>

app/views/flats/new.html.erb
<div id="form_new">
  <%= simple_form_for(@flat) do |f| %>
    <%= f.input :name %>
    <%= f.input :adress%>
    <%= f.input :rooms %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Add my pokemon !", class: "btn-ghost" %>
  <% end %>
</div>

app/views/flats/show.html.erb
<%= @flat.name %>
<% if @flat.photo.attached? %>
  <%= cl_image_tag @flat.photo.key, height: 300, class: "img-card-top" %>
<% else%>
  <%= "METTRE UNE IMAGE" %>
<% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LocateMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
    <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Le Wagon brings <strong>tech skills</strong> to <strong>creative people</strong>!</h1>
    <p>Change your life and learn to code at one of our campuses around the world.</p>
    <a class="btn btn-flat" href="#">Apply now</a>
  </div>
</div>
  <%= link_to "Appartements",flats_path %>
<h1>HOMEPAGE</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" />
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Messages</a>
          </li>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
              <a class="dropdown-item" href="#">Another action</a>
            </div>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>